language: node_js
node_js:
  - "8"
branches:
  except:
  - gh-pages
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      # before_install: npm i -g codecov
      install: npm install
      script: npm test
      # after_success: codecov
    - stage: lint
      script: npm run tslint
    - stage: build
      script: npm run build
      deploy:
        provider: pages
        local-dir: build
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        fqdn: francesco-agnoletto.com
        on:
          branch: master
    - if: branch = /^greenkeeper\/.*$
      before_install:
      - npm install -g greenkeeper-lockfile
      install: npm install
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
