language: node_js
node_js:
  - "8"
branches:
  except:
    - gh-pages
cache:
  directories:
    - "node_modules"

before_install:
  - if [[ `npm -v` != 5.10* ]]; then npm i -g npm@5.10; fi
  - npm i -g greenkeeper-lockfile@2 codecov

install:
  - npm install

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run type-check
  - npm run tslint
  - npm test
  - npm run build

after_script:
  - codecov
  - greenkeeper-lockfile-upload

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  fqdn: francesco-agnoletto.com
  on:
    branch: master
